USE DW_NESTAREZ;
GO

INSERT INTO DIM_TIEMPO
(
    ID_FECHA,
    FECHA,
    DIA,
    NOMBRE_DIA,
    MES,
    NOMBRE_MES,
    TRIMESTRE,
    ANIO
)
SELECT DISTINCT

    CONVERT(INT,
        FORMAT(CONVERT(DATE, FECHA_VENTA, 103),'yyyyMMdd')
    ) AS ID_FECHA,

    CONVERT(DATE, FECHA_VENTA,103),

    DAY(CONVERT(DATE, FECHA_VENTA,103)),

    DATENAME(WEEKDAY,CONVERT(DATE, FECHA_VENTA,103)),

    MONTH(CONVERT(DATE, FECHA_VENTA,103)),

    DATENAME(MONTH,CONVERT(DATE, FECHA_VENTA,103)),

    DATEPART(QUARTER,CONVERT(DATE, FECHA_VENTA,103)),

    YEAR(CONVERT(DATE, FECHA_VENTA,103))

FROM STAGING_NESTAREZ.dbo.STG_VENTAS

WHERE FECHA_VENTA IS NOT NULL

AND NOT EXISTS
(
    SELECT 1
    FROM DIM_TIEMPO D
    WHERE D.ID_FECHA =
        CONVERT(INT,
        FORMAT(CONVERT(DATE, FECHA_VENTA,103),'yyyyMMdd'))
);
GO

------------
USE DW_NESTAREZ;
GO

INSERT INTO DIM_PRODUCTO
(
    NOMBRE_PRODUCTO,
    CATEGORIA
)
SELECT DISTINCT

    PRODUCTO,
    CATEGORIA

FROM STAGING_NESTAREZ.dbo.STG_VENTAS

WHERE PRODUCTO IS NOT NULL
AND CATEGORIA IS NOT NULL

AND NOT EXISTS
(
    SELECT 1
    FROM DIM_PRODUCTO DP
    WHERE DP.NOMBRE_PRODUCTO = STG_VENTAS.PRODUCTO
);
GO
-----------

USE DW_NESTAREZ;
GO

INSERT INTO DIM_SUCURSAL
(
    NOMBRE_SUCURSAL,
    DIRECCION,
    TELEFONO,
    HORA_APERTURA,
    HORA_CIERRE
)
SELECT DISTINCT

    SUCURSAL,
    DIRECCION_SUCURSAL,

    'NO REGISTRADO',

    '07:00',

    '20:00'

FROM STAGING_NESTAREZ.dbo.STG_VENTAS

WHERE SUCURSAL IS NOT NULL

AND NOT EXISTS
(
    SELECT 1
    FROM DIM_SUCURSAL DS
    WHERE DS.NOMBRE_SUCURSAL = STG_VENTAS.SUCURSAL
);
GO
---------------
USE DW_NESTAREZ;
GO

INSERT INTO FACT_VENTAS
(
    ID_FECHA,
    ID_PRODUCTO,
    ID_SUCURSAL,
    CANTIDAD_VENDIDA,
    PRECIO_UNITARIO,
    TOTAL_VENTA
)

SELECT

    DT.ID_FECHA,

    DP.ID_PRODUCTO,

    DS.ID_SUCURSAL,

    CAST(S.CANTIDAD_VENDIDA AS INT),

    CAST(S.PRECIO_UNITARIO AS DECIMAL(10,2)),

    CAST(S.TOTAL_VENTA AS DECIMAL(12,2))

FROM STAGING_NESTAREZ.dbo.STG_VENTAS S

INNER JOIN DIM_TIEMPO DT
ON DT.ID_FECHA =
CONVERT(INT,
FORMAT(CONVERT(DATE,S.FECHA_VENTA,103),'yyyyMMdd'))

INNER JOIN DIM_PRODUCTO DP
ON DP.NOMBRE_PRODUCTO = S.PRODUCTO

INNER JOIN DIM_SUCURSAL DS
ON DS.NOMBRE_SUCURSAL = S.SUCURSAL

WHERE S.ESTADO_STG='OK';
GO
---

SELECT COUNT(*) AS TOTAL_TIEMPO
FROM DIM_TIEMPO;

SELECT COUNT(*) AS TOTAL_PRODUCTOS
FROM DIM_PRODUCTO;

SELECT COUNT(*) AS TOTAL_SUCURSALES
FROM DIM_SUCURSAL;

SELECT COUNT(*) AS TOTAL_VENTAS
FROM FACT_VENTAS;
select * from FACT_VENTAS

