/*=========================================================
    STAGING AREA
    PANADERIA Y PASTELERIA NESTAREZ
=========================================================*/

CREATE DATABASE STAGING_NESTAREZ;
GO

USE STAGING_NESTAREZ;
GO

CREATE TABLE STG_VENTAS
(
    ID_STG BIGINT IDENTITY(1,1) PRIMARY KEY,

    FECHA_VENTA NVARCHAR(30),

    PRODUCTO NVARCHAR(150),

    CATEGORIA NVARCHAR(100),

    SUCURSAL NVARCHAR(100),

    DIRECCION_SUCURSAL NVARCHAR(250),

    CANTIDAD_VENDIDA NVARCHAR(20),

    PRECIO_UNITARIO NVARCHAR(20),

    TOTAL_VENTA NVARCHAR(20),

    ARCHIVO_ORIGEN NVARCHAR(150),

    ESTADO_STG NVARCHAR(20) DEFAULT 'PENDIENTE',

    FECHA_CARGA DATETIME DEFAULT GETDATE()
);
GO

CREATE TABLE ETL_LOG
(
    ID_LOG INT IDENTITY(1,1) PRIMARY KEY,

    ARCHIVO_PROCESADO VARCHAR(200),

    REGISTROS_LEIDOS INT,

    REGISTROS_INSERTADOS INT,

    FECHA_EJECUCION DATETIME DEFAULT GETDATE(),

    ESTADO VARCHAR(50)
);
GO
select * from ETL_LOG;
select *  from STG_VENTAS;
USE STAGING_NESTAREZ;
GO

PRINT '========================================';
PRINT 'TOTAL GENERAL DE REGISTROS';
PRINT '========================================';

SELECT
    COUNT(*) AS TOTAL_REGISTROS
FROM STG_VENTAS;

PRINT '========================================';
PRINT 'TOTAL DE REGISTROS POR SUCURSAL';
PRINT '========================================';

SELECT
    SUCURSAL,
    COUNT(*) AS TOTAL_REGISTROS
FROM STG_VENTAS
GROUP BY SUCURSAL
ORDER BY TOTAL_REGISTROS DESC;

PRINT '========================================';
PRINT 'TOTAL DE REGISTROS POR ANIO';
PRINT '========================================';

SELECT
    YEAR(CONVERT(DATE, FECHA_VENTA, 103)) AS ANIO,
    COUNT(*) AS TOTAL_REGISTROS
FROM STG_VENTAS
GROUP BY YEAR(CONVERT(DATE, FECHA_VENTA, 103))
ORDER BY ANIO;

PRINT '========================================';
PRINT 'TOTAL DE REGISTROS POR SUCURSAL Y ANIO';
PRINT '========================================';

SELECT
    SUCURSAL,
    YEAR(CONVERT(DATE, FECHA_VENTA, 103)) AS ANIO,
    COUNT(*) AS TOTAL_REGISTROS
FROM STG_VENTAS
GROUP BY
    SUCURSAL,
    YEAR(CONVERT(DATE, FECHA_VENTA, 103))
ORDER BY
    SUCURSAL,
    ANIO;

PRINT '========================================';
PRINT 'TOTAL DE REGISTROS POR ARCHIVO';
PRINT '========================================';





SELECT
    ARCHIVO_ORIGEN,
    COUNT(*) AS TOTAL_REGISTROS
FROM STG_VENTAS
GROUP BY ARCHIVO_ORIGEN
ORDER BY ARCHIVO_ORIGEN;









PRINT '========================================';
PRINT 'VALIDACION FINAL';
PRINT '========================================';

SELECT
    COUNT(DISTINCT ARCHIVO_ORIGEN) AS TOTAL_ARCHIVOS_CARGADOS,
    COUNT(*) AS TOTAL_REGISTROS_CARGADOS
FROM STG_VENTAS;
GO


