--TRANSFORMACION 1
UPDATE STG_VENTAS
SET PRODUCTO = LTRIM(RTRIM(PRODUCTO));
SELECT DISTINCT PRODUCTO
FROM STG_VENTAS
ORDER BY PRODUCTO;

   SELECT *
FROM STG_VENTAS
WHERE FECHA_VENTA = 'FECHA'
   OR PRODUCTO = 'PRODUCTO';

-- TRANSFORMACION 2
UPDATE STG_VENTAS
SET CATEGORIA = LTRIM(RTRIM(CATEGORIA));

SELECT DISTINCT CATEGORIA
FROM STG_VENTAS
ORDER BY CATEGORIA;
--TRNASFORMACION 3

SELECT
    CANTIDAD_VENDIDA,
    TRY_CAST(CANTIDAD_VENDIDA AS INT) AS CANTIDAD_NUMERICA
FROM STG_VENTAS;

--TRANSFORMACION 4
SELECT
    PRECIO_UNITARIO,
    TRY_CAST(PRECIO_UNITARIO AS DECIMAL(10,2)) AS PRECIO_NUMERICO
FROM STG_VENTAS;
--TRANSFORMACION 5
SELECT
    TOTAL_VENTA,
    TRY_CAST(TOTAL_VENTA AS DECIMAL(12,2)) AS TOTAL_NUMERICO
FROM STG_VENTAS;

--transformacion 6
DELETE FROM STG_VENTAS
WHERE FECHA_VENTA IS NULL;



--transformacion 7
SELECT
    FECHA_VENTA,
    YEAR(CONVERT(DATE,FECHA_VENTA,103)) AS ANIO,
    MONTH(CONVERT(DATE,FECHA_VENTA,103)) AS MES
FROM STG_VENTAS;

--transformacion 8
SELECT
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT PRODUCTO) AS TOTAL_PRODUCTOS,
    COUNT(DISTINCT CATEGORIA) AS TOTAL_CATEGORIAS,
    COUNT(DISTINCT SUCURSAL) AS TOTAL_SUCURSALES
FROM STG_VENTAS;


SELECT *
FROM STAGING_NESTAREZ.dbo.STG_VENTAS
WHERE DIRECCION_SUCURSAL IS NULL;
USE DW_NESTAREZ;
GO

--transformacion 9

USE STAGING_NESTAREZ;
GO

UPDATE STG_VENTAS
SET ESTADO_STG = 'OK'
WHERE
    FECHA_VENTA IS NOT NULL
    AND PRODUCTO IS NOT NULL
    AND SUCURSAL IS NOT NULL
    AND CANTIDAD_VENDIDA IS NOT NULL
    AND PRECIO_UNITARIO IS NOT NULL
    AND TOTAL_VENTA IS NOT NULL;
GO

USE STAGING_NESTAREZ;
GO

SELECT
    ESTADO_STG,
    COUNT(*) AS TOTAL_REGISTROS
FROM STG_VENTAS
GROUP BY ESTADO_STG;
GO

USE STAGING_NESTAREZ;
GO
--transformacion 10 


SELECT
    COUNT(*) AS TOTAL_REGISTROS,

    SUM(CASE
            WHEN ESTADO_STG = 'OK'
            THEN 1
            ELSE 0
        END) AS REGISTROS_OK,

    SUM(CASE
            WHEN ESTADO_STG = 'ERROR'
            THEN 1
            ELSE 0
        END) AS REGISTROS_ERROR,

    CAST(
        SUM(CASE
                WHEN ESTADO_STG = 'OK'
                THEN 1
                ELSE 0
            END) * 100.0 / COUNT(*)
        AS DECIMAL(10,2)
    ) AS PORCENTAJE_OK,

    CAST(
        SUM(CASE
                WHEN ESTADO_STG = 'ERROR'
                THEN 1
                ELSE 0
            END) * 100.0 / COUNT(*)
        AS DECIMAL(10,2)
    ) AS PORCENTAJE_ERROR

FROM STG_VENTAS;
GO